// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldEngine.Infrastructure.Persistence;

#nullable disable

namespace WorldEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorldEngineDbContext))]
    [Migration("20260812162400_AddAgentsAndEvents")]
    partial class AddAgentsAndEvents
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldEngine.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Aggression")
                        .HasColumnType("double precision");

                    b.Property<bool>("Alive")
                        .HasColumnType("boolean");

                    b.Property<double>("Ambition")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BirthSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Curiosity")
                        .HasColumnType("double precision");

                    b.Property<string>("DeathCause")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DeathSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Discipline")
                        .HasColumnType("double precision");

                    b.Property<double>("Empathy")
                        .HasColumnType("double precision");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision");

                    b.Property<double>("Generosity")
                        .HasColumnType("double precision");

                    b.Property<double>("Happiness")
                        .HasColumnType("double precision");

                    b.Property<double>("Health")
                        .HasColumnType("double precision");

                    b.Property<double>("Hunger")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Money")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("RiskTolerance")
                        .HasColumnType("double precision");

                    b.Property<double>("Safety")
                        .HasColumnType("double precision");

                    b.Property<double>("Sociability")
                        .HasColumnType("double precision");

                    b.Property<double>("SocialNeed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "Alive");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.SimulationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TargetAgentId")
                        .HasColumnType("uuid");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "EventType");

                    b.HasIndex("WorldId", "SimulationTime");

                    b.ToTable("simulation_events", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("integer");

                    b.Property<double>("SimulationSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TickNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("worlds", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
