// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using WorldEngine.Infrastructure.Persistence;

#nullable disable

namespace WorldEngine.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(WorldEngineDbContext))]
    [Migration("20260812191911_AddSettlementsAndGroups")]
    partial class AddSettlementsAndGroups
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("WorldEngine.Domain.Entities.Agent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<double>("Aggression")
                        .HasColumnType("double precision");

                    b.Property<bool>("Alive")
                        .HasColumnType("boolean");

                    b.Property<double>("Ambition")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("BirthSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Curiosity")
                        .HasColumnType("double precision");

                    b.Property<string>("DeathCause")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<DateTime?>("DeathSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Discipline")
                        .HasColumnType("double precision");

                    b.Property<double>("Empathy")
                        .HasColumnType("double precision");

                    b.Property<double>("Energy")
                        .HasColumnType("double precision");

                    b.Property<double>("Generosity")
                        .HasColumnType("double precision");

                    b.Property<double>("Happiness")
                        .HasColumnType("double precision");

                    b.Property<double>("Health")
                        .HasColumnType("double precision");

                    b.Property<double>("Hunger")
                        .HasColumnType("double precision");

                    b.Property<string>("Location")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<decimal>("Money")
                        .HasColumnType("numeric(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Occupation")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<double>("RiskTolerance")
                        .HasColumnType("double precision");

                    b.Property<double>("Safety")
                        .HasColumnType("double precision");

                    b.Property<double>("Sociability")
                        .HasColumnType("double precision");

                    b.Property<double>("SocialNeed")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "Alive");

                    b.ToTable("agents", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.AgentDecisionRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("AvailableActionsJson")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DecisionSource")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("FallbackUsed")
                        .HasColumnType("boolean");

                    b.Property<int?>("LatencyMs")
                        .HasColumnType("integer");

                    b.Property<string>("ModelName")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("PromptVersion")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Reasoning")
                        .HasColumnType("text");

                    b.Property<string>("SelectedActionId")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("SelectedActionType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("SelectedScore")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("SimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("AgentId", "DecidedAt");

                    b.ToTable("agent_decisions", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.AgentInventory", b =>
                {
                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("AgentId", "ResourceType");

                    b.ToTable("agent_inventories", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.AgentMemory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CreatedSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("EmotionalImpact")
                        .HasColumnType("double precision");

                    b.Property<double>("Importance")
                        .HasColumnType("double precision");

                    b.Property<Guid?>("OtherAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("SimulationEventId")
                        .HasColumnType("uuid");

                    b.Property<string>("Summary")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("AgentId", "CreatedSimulationTime");

                    b.HasIndex("SimulationEventId", "AgentId")
                        .IsUnique();

                    b.ToTable("agent_memories", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.AgentRelationship", b =>
                {
                    b.Property<Guid>("SourceAgentId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("TargetAgentId")
                        .HasColumnType("uuid");

                    b.Property<double>("Affection")
                        .HasColumnType("double precision");

                    b.Property<double>("Anger")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<double>("Familiarity")
                        .HasColumnType("double precision");

                    b.Property<double>("Fear")
                        .HasColumnType("double precision");

                    b.Property<double>("Respect")
                        .HasColumnType("double precision");

                    b.Property<double>("Trust")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("SourceAgentId", "TargetAgentId");

                    b.ToTable("agent_relationships", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("FormationReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<DateTime>("FormationSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.ToTable("groups", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.GroupMembership", b =>
                {
                    b.Property<Guid>("GroupId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("AgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("JoinedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.HasKey("GroupId", "AgentId");

                    b.ToTable("group_memberships", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.Location", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "Name")
                        .IsUnique();

                    b.ToTable("locations", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.LocationResource", b =>
                {
                    b.Property<Guid>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<double>("Quantity")
                        .HasColumnType("double precision");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("LocationId", "ResourceType");

                    b.ToTable("location_resources", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.Settlement", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CenterLocationName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTime>("CreationSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("FirstPopulationAtTick")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("FormationReason")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("Population")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId");

                    b.HasIndex("WorldId", "CenterLocationName")
                        .IsUnique();

                    b.ToTable("settlements", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.SimulationEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<Guid?>("ActorAgentId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Data")
                        .IsRequired()
                        .HasColumnType("jsonb");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<Guid?>("LocationId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("SimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("TargetAgentId")
                        .HasColumnType("uuid");

                    b.Property<long>("Tick")
                        .HasColumnType("bigint");

                    b.Property<Guid>("WorldId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("WorldId", "EventType");

                    b.HasIndex("WorldId", "SimulationTime");

                    b.ToTable("simulation_events", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.World", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("CurrentSimulationTime")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("RandomSeed")
                        .HasColumnType("integer");

                    b.Property<double>("SimulationSpeed")
                        .HasColumnType("double precision");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<long>("TickNumber")
                        .HasColumnType("bigint");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("Name");

                    b.ToTable("worlds", (string)null);
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.AgentInventory", b =>
                {
                    b.HasOne("WorldEngine.Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("AgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.AgentRelationship", b =>
                {
                    b.HasOne("WorldEngine.Domain.Entities.Agent", null)
                        .WithMany()
                        .HasForeignKey("SourceAgentId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.GroupMembership", b =>
                {
                    b.HasOne("WorldEngine.Domain.Entities.Group", null)
                        .WithMany()
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("WorldEngine.Domain.Entities.LocationResource", b =>
                {
                    b.HasOne("WorldEngine.Domain.Entities.Location", null)
                        .WithMany()
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
